services:
  - type: web
    name: honey-inventory
    runtime: docker
    repo: https://github.com/stevenmwaanda14-tech/HoneyInventorySystem
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: JAVA_OPTS
        value: -Xmx256m